#!/usr/bin/env bash
# config for ubuntu server so localhost is 127.0.0.2 & facebook.com is 8.8.8.8
sed -i 's/127.0.0.1\s*localhost/127.0.0.2 localhost/' /etc/hosts
if grep -q "facebook.com" /etc/hosts; then
    sed -i 's/.*facebook\.com.*/8.8.8.8 facebook.com/' /etc/hosts
else
    echo "8.8.8.8 facebook.com" >> /etc/hosts
fi
